# Generated by Django 4.0.3 on 2022-03-23 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=100)),
                ('data_publi', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.editora')),
            ],
        ),
    ]
